name: Build Multi-Arch Dockers 

on:
  workflow_dispatch:
  push:
    branches: multi-docker

jobs:
  find-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
  build:
    runs-on: ubuntu-latest
    needs: find-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
           ref: refs/tags/${{ find.latest.steps.previoustag.outputs.tag }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
          --tag iamklh/xbvr:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
