name: Build Multi-Arch Dockers 

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  find-latest:
    env: 
      prevtag: 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
#        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        run: |
          git describe --abbrev=0 --tags >> "${{ env.prevtag }}"
          echo "${{env.prevtag}}"
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          exclude: '*beta*'
#          include: '0.3.*'
          commit-ish: 'HEAD~'
        # if you unshallow in a separate step, use the following option:
          skip-unshallow: 'true'
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
          echo 'prevtag=${{steps.tagger.outputs.tag}}' >> $GITHUB_ENV
          echo 'Output from copy Tag: ${{env.prvtag}}'

  build:
    runs-on: ubuntu-latest
    needs: find-latest
    steps:
      - name: checkit     
        run: echo "tag = ${{ env.prevtag }}"
      - name: checkout code
        uses: actions/checkout@v2
        with:
           ref: refs/tags/${{ env.prevtag }}
# https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
# https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
          --tag iamklh/xbvr:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
