name: Build Multi-Arch Dockers 

on:
  workflow_dispatch:
  push:
    branches: master
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Optionally: unshallow as a separate operation
    # - name: Unshallow
    #   run: git fetch --prune --unshallow
    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v1
    - name: Show Tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

  build:
    runs-on: ubuntu-latest
    needs: find-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
           ref: refs/tags/${{ env.prevtag }}
# https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
# https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
          --tag iamklh/xbvr:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
