name: Build Multi-Arch Dockers 

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  find-latest:
    env: 
      prevtag: 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
#        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        run: git describe --abbrev=0 --tags >> ${{ env.prevtag }}
  build:
    runs-on: ubuntu-latest
    needs: find-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
           ref: refs/tags/${{ env.prevtag }}
# https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
# https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
          --tag iamklh/xbvr:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
