name: Publish Docker images

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  publish-docker-image-latest:
    runs-on: ubuntu-22.04
    name: Publish Docker image from master branch
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Install dependencies
        run: echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list && sudo apt-get update && sudo apt-get install -y gcc-mingw-w64 goreleaser zip
      - name: Check out XBVR repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build UI
        run: cd ui && yarn install && yarn build
      - name: Patch nightly version # We change v0.0.0-next version to CURRENT to avoid update prompt
        run: sed -i 's/{{ \.Tag }}-next/CURRENT/g' .goreleaser.yml
      - name: Release nightly package
        run: PATH=$PATH:$HOME/go/bin goreleaser build --id xbvr-linux-amd64 --snapshot --rm-dist && mv dist/xbvr-linux-amd64_linux_amd64_v1/xbvr ./xbvr
      - name: Push to Container Registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: coolmintchocolate
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: coolmintchocolate/xbvr
          push: true
          tags: latest

  publish-docker-image-dev:
    runs-on: ubuntu-22.04
    name: Publish Docker image from dev branch
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Install dependencies
        run: echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list && sudo apt-get update && sudo apt-get install -y gcc-mingw-w64 goreleaser zip
      - name: Check out XBVR repo
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Build UI
        run: cd ui && yarn install && yarn build
      - name: Patch nightly version # We change v0.0.0-next version to CURRENT to avoid update prompt
        run: sed -i 's/{{ \.Tag }}-next/CURRENT/g' .goreleaser.yml
      - name: Release nightly package
        run: PATH=$PATH:$HOME/go/bin goreleaser build --id xbvr-linux-amd64 --snapshot --rm-dist && mv dist/xbvr-linux-amd64_linux_amd64_v1/xbvr ./xbvr
      - name: Push to Container Registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: coolmintchocolate
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: coolmintchocolate/xbvr
          push: true
          tags: dev
