name: release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          ref: master     
          submodules: 'true'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build UI
        run:  cd ui && yarn install && yarn build

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env
          echo 'GITHUB_USER=${{github.event.repository.owner.login}}' >> .release-env
          echo GITHUB_PROJECT=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> .release-env
          echo 'DOCKER_CREDS_FILE=.docker-creds' >> .release-env
          echo '${{github.event.repository.owner.login}}:${{ secrets.GITHUB_TOKEN }}:ghcr.io' >> .docker-creds
