name: release

on:
  push:
    tags:
      - "*"

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build UI
        run:  cd ui && yarn install && yarn build

      - name: zeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
          echo 'GITHUB_USER=${{github.event.repository.owner.login}}' >> .release-env
          echo GITHUB_PROJECT=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> .release-env
          echo 'DOCKER_CREDS_FILE=.docker-creds' >> .release-env
          echo '${{github.event.repository.owner.login}}:${{ secrets.GITHUB_TOKEN }}:ghcr.io' >> .docker-creds

      - name: Release publish
        run: make release

      - name: POST release
        run: curl --dns-servers ${{ secrets.XBVR_DNS }} -k -X POST -i ${{ secrets.XBVR_CONTAINER }}      
        
      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'RELEASE deployment COMPLETE'
