name: build UNOFFICIAL

on:
  schedule:
    - cron: "20 14,18 * * *"
  workflow_dispatch:
  push:
    branches: master

jobs:
  DH:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          git checkout github.com/therealklh/xbvr/util Dockerfile .yarnrc
          docker buildx build --push \
          --tag iamklh/xbvr:notofficial \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
  GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: util/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/therealklh/xbvr:almostofficial          
  PUSH:
    needs: [DH, GHCR]
    runs-on: ubuntu-latest
    if: ${{github.event.action == 'push' }}
    steps:
      - uses: actions/checkout@v2 # required to clone your code
      - name: Report Pushing
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'MASTER has been updated!'      

